version: '3'

services:
  geoserver:
    build:
      context: .
      args: 
        GEOSERVER_PLUGINS: "css pyramid"
    image: meteofi/geoserver:2.20
    container_name: geoserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - geoserver-storage:/data/geoserver

volumes:
  geoserver-storage:
